Expose more information to python functions
automl/random_forest_run pull request #64
Opened 2021-07-15 21:00 UTC by dengdifan

Additional RF components (trees, nodes, and splits) are now exposed to the python functions and thus more interactions are allowed

2021-08-23 08:22 UTC, AndreBiedenkapp requested changes
Sorry for the late review. I only got notified once @mfeurer assigned me as reviewer.
There are only two minor changes that need to be done before we can merge this PR.

2021-08-23 08:22 UTC, AndreBiedenkapp commented on include/rfr/nodes/k_ary_node.hpp
> +	//TODO do we need to store all the data indices in all nodes or only in leaf nodes
Is this TODO resolved by now?

2021-08-23 08:22 UTC, AndreBiedenkapp commented on include/rfr/nodes/k_ary_node.hpp
> +#endif":wq"
Could you please remove this artifact :)

2021-08-31 08:12 UTC, dengdifan commented
I updated the PR with your comment, I'll later add some tests accordingly

2021-11-08 07:56 UTC, merged